[package]
name = "ruffle_macros"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"

[dependencies.syn]
version = "1.0.58"
features = ["full"]
